apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zoneminder.fullname" . }}-config-pvc
spec:
  accessModes:
    - ReadWriteOnce # not ReadWriteMany because image doesn't have mount.nfs
  resources:
    requests:
      storage: {{ .Values.storage.config.size }}
  storageClassName: {{ .Values.storage.config.className }}